<?php

// $Id$
// Author: Eugen Mayer (http://kontextwork.de)
// Copyright 2010

function tagging_opencalais_suggest_tagging_suggestions($vid, $node) {
  $suggestions = array();
  if (is_array($node->body)) {
    $text = implode(' ', array_values($node->body));
  } else {
    $text = $node->body;
  }
  $result = calais_api_analyze_xml($node->title, $text, $node->created);
  foreach ($result as $categorie) {
    if ($categorie->type == 'URL') {
      continue;
    }

    foreach ($categorie->terms as $term) {
      $suggestions[] = array('#name' => $term->name, '#weight' => $term->relevance);
    }
  }
  return $suggestions;
}